pipeline {
    agent any
    tools { 
        maven 'maven-3.8.6'
        dockerTool 'docker'
    }
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Create Tomcat Docker Image'){
            steps {
                sh "pwd"
                sh "ls -a"
                sh "docker build java-tomcat -t tomcatsamplewebapp:${env.BUILD_ID}"
                sh "docker run -itd -p 8085:8080 tomcatsamplewebapp:${env.BUILD_ID}"
                sh "docker ps"
            }
        }

    }
}